Repository AY1920S1-CS2103T-F14-3/main, pull requests merged in 2019-11, with the labels that each got.

#142 Update UG
  docs/UserGuide.adoc
  docs/images/GameOver.png
  docs/images/StartWindow.png
Labels: documentation

#143 Update UI component in DG
  docs/DeveloperGuide.adoc
Labels: documentation

#191 Fix game issues and update documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/GameWindowClassDiagram.puml
  docs/images/GameWindowClassDiagram.png
  docs/images/Typee_UML-Architecture.png
  src/main/java/com/typee/game/Player.java
  src/main/java/com/typee/game/Words.java
  src/main/java/com/typee/ui/game/GameBody.java
  src/main/java/com/typee/ui/game/GameWindow.java
  src/main/java/com/typee/ui/game/MovingWord.java
  src/main/java/com/typee/ui/game/TextHighlighter.java
  src/main/resources/view/GameWindow.fxml
Labels: Type.Enhancement

#198 Implement Find Command
  src/main/java/com/typee/logic/commands/FindCommand.java
  src/main/java/com/typee/logic/parser/FindCommandParser.java
  src/main/java/com/typee/model/engagement/EngagementPredicate.java
  src/main/java/com/typee/model/person/DescriptionContainsKeywordsPredicate.java
  src/main/java/com/typee/ui/game/GameWindow.java
  src/test/java/com/typee/logic/commands/CommandTestUtil.java
  src/test/java/com/typee/logic/parser/TypeeParserTest.java
Labels: Type.Enhancement

#200 Improves in Pdf Command
  src/main/java/com/typee/commons/util/PdfUtil.java
  src/main/java/com/typee/logic/commands/PdfCommand.java
  src/main/java/com/typee/logic/commands/exceptions/DeleteDocumentException.java
  src/main/java/com/typee/logic/commands/exceptions/GenerateExistingReportException.java
  src/main/java/com/typee/model/Model.java
  src/main/java/com/typee/model/ModelManager.java
  src/main/java/com/typee/model/report/Report.java
  src/main/java/com/typee/ui/report/ReportWindow.java
  src/test/java/com/typee/commons/util/PdfUtilTest.java
  src/test/java/com/typee/logic/commands/AddCommandTest.java
  src/test/java/com/typee/logic/commands/PdfCommandTest.java
Labels: Type.Enhancement, priority.High, status.Ongoing

#201 implements unit test for ModelManager class
  src/main/java/com/typee/model/Model.java
  src/main/java/com/typee/model/ModelManager.java
  src/test/java/com/typee/logic/commands/AddCommandTest.java
  src/test/java/com/typee/model/ModelManagerTest.java
  src/test/java/com/typee/testutil/TypicalReports.java
Labels: Type.Enhancement, status.Ongoing

#208 implements auto opening document.
  src/main/java/com/typee/commons/util/PdfUtil.java
  src/main/java/com/typee/logic/commands/CommandResult.java
  src/main/java/com/typee/logic/commands/PdfCommand.java
  src/main/java/com/typee/model/Model.java
  src/main/java/com/typee/model/ModelManager.java
  src/main/java/com/typee/ui/MainWindow.java
  src/test/java/com/typee/logic/commands/AddCommandTest.java
Labels: Type.Enhancement

#213 Fix unit tests
  src/main/java/com/typee/logic/interactive/parser/ArgumentMultimap.java
  src/main/java/com/typee/logic/interactive/parser/InteractiveParserUtil.java
  src/main/java/com/typee/logic/interactive/parser/state/State.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarstate/CalendarState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarstate/OpenDisplayState.java
  src/main/java/com/typee/ui/calendar/CalendarDateCell.java
  src/main/java/com/typee/ui/calendar/CalendarWindow.java
  src/main/java/com/typee/ui/calendar/exceptions/CalendarCloseDisplayException.java
  src/test/java/com/typee/logic/interactive/parser/state/CalendarStateTest.java
Labels: status.Ongoing

#206 Adding Unit tests
  .gitignore
  src/main/java/com/typee/commons/util/JsonUtil.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/data/sandbox/invalidList.json
  src/test/data/sandbox/serializeList.json
  src/test/java/com/typee/commons/util/JsonUtilTest.java
  src/test/java/com/typee/commons/util/PdfUtilTest.java
  src/test/java/com/typee/logic/commands/PdfCommandTest.java
  src/test/java/com/typee/logic/commands/TabCommandTest.java
  src/test/java/com/typee/model/ModelManagerTest.java
  src/test/java/com/typee/testutil/SerializableListTestClass.java
Labels: help wanted, priority.High

#217 Changes in UI (Tab Menu layout modified)
  src/main/java/com/typee/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TabPanel.fxml
Labels: Type.Enhancement, status.Ongoing

#218 adjustments in resizing mainwindow.
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.Low

#223 Updates in UI (Layout) & some functionalities
  src/main/java/com/typee/commons/util/PdfUtil.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/TabPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EngagementCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: Type.Enhancement, priority.Medium, severity.Low, status.Ongoing

#216 Fix unit tests
  src/main/java/com/typee/logic/commands/HelpCommand.java
  src/main/java/com/typee/logic/commands/ListCommand.java
  src/main/java/com/typee/logic/interactive/parser/CliSyntax.java
  src/main/java/com/typee/logic/interactive/parser/Parser.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/CalendarState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/CloseDisplayEndState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/CloseDisplayState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/NextMonthState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/OpenDisplayEndState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/OpenDisplayState.java
  src/main/java/com/typee/logic/interactive/parser/state/calendarmachine/PreviousMonthState.java
  src/main/java/com/typee/logic/interactive/parser/state/helpmachine/HelpState.java
  src/main/java/com/typee/logic/interactive/parser/state/listmachine/ListState.java
  src/test/java/com/typee/logic/commands/HelpCommandTest.java
  src/test/java/com/typee/logic/commands/ListCommandTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/CalendarStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/CloseDisplayEndStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/CloseDisplayStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/NextMonthStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/OpenDisplayEndStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/OpenDisplayStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/calendarmachine/PreviousMonthStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/helpmachine/HelpStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/listmachine/ListStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/redomachine/RedoStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/sortmachine/OrderStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/sortmachine/PropertyStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/sortmachine/SortEndStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/undomachine/UndoStateTest.java
Labels: status.Ongoing

#228 Fix unit tests
  src/main/java/com/typee/logic/commands/ClearCommand.java
  src/main/java/com/typee/logic/interactive/parser/state/State.java
  src/main/java/com/typee/logic/interactive/parser/state/clearmachine/ClearState.java
  src/main/java/com/typee/logic/interactive/parser/state/deletemachine/DeleteEndState.java
  src/main/java/com/typee/logic/interactive/parser/state/deletemachine/IndexState.java
  src/main/java/com/typee/ui/calendar/CalendarWindow.java
  src/test/java/com/typee/logic/commands/ClearCommandTest.java
  src/test/java/com/typee/logic/interactive/parser/state/clearmachine/ClearStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/deletemachine/DeleteEndStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/deletemachine/IndexStateTest.java
Labels: status.Ongoing

#226 implements unit test for Pdfmachine
  src/test/java/com/typee/logic/interactive/parser/state/pdfmachine/FromStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/pdfmachine/PdfEndStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/pdfmachine/PdfIndexStateTest.java
  src/test/java/com/typee/logic/interactive/parser/state/pdfmachine/ToStateTest.java
Labels: Type.Enhancement, priority.High

#204 Updates in PPP and User Guide
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/pdf_1.png
  docs/images/pdf_2.png
  docs/images/pdf_delete.png
  docs/images/pdf_delete_after.png
  docs/images/pdf_error_1.png
  docs/images/pdf_error_2.png
  docs/images/pdf_function_btns.png
  docs/images/ppp_nordic96/ppp_1.png
  docs/images/tab_1_default.png
  docs/images/tab_2.png
  docs/images/tab_3.png
  docs/team/nordic96.adoc
Labels: documentation

#249 Final Updates in PPP and other documentations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/GenerateReportSequenceDiagram.puml
  docs/diagrams/PdfCommandClassDiagram.puml
  docs/diagrams/PdfUtilClassDiagram.puml
  docs/diagrams/TabClassDiagram.puml
  docs/diagrams/TabCommandClassDiagram.puml
  docs/diagrams/fetchTabInformationActivityDiagram.puml
  docs/images/GenerateReportSequenceDiagram.png
  docs/images/PdfCommandClassDiagram.png
  docs/images/PdfUtilClassDiagram.png
  docs/images/TabClassDiagram.png
  docs/images/TabCommandClassDiagram.png
  docs/images/fetchTabInformationActivityDiagram.png
  docs/images/pdf_1.png
  docs/images/pdf_delete_before_after.png
  docs/images/ppp_nordic96/ppp_1.png
  docs/images/tab_1_default.png
  docs/images/tab_2.png
  docs/images/tab_3.png
  docs/images/tabcmd_and_tabFetch_activity.png
  docs/team/nordic96.adoc
  docs/team/nordic96.pdf
  src/main/java/com/typee/ui/Tab.java
Labels: documentation

#259 Developer guide gihun
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/GenerateReportSequenceDiagram.puml
  docs/images/GenerateReportSequenceDiagram.png
  docs/team/nordic96.adoc
  docs/team/nordic96.pdf
Labels: documentation
