Repository AY1920S1-CS2103T-F14-3/main, pull requests merged in 2019-10, with the labels that each got.

#2 Updates User Guide and Developer's Guide
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/gihunk.jpg
Labels: documentation

#12 Gihun - replace profile picture from jpg to png and renaming responsibilities
  docs/AboutUs.adoc
  docs/images/gihunk.png
Labels: documentation

#39 replace image file to github account name
  docs/AboutUs.adoc
  docs/images/nordic96.png
Labels: documentation

#57 update DG with user stories
  docs/DeveloperGuide.adoc
Labels: documentation

#58 resolving merge conflicts in Developer's Guide
  docs/DeveloperGuide.adoc
Labels: documentation

#60 Updates Developer's Guide
  build.gradle
  docs/DeveloperGuide.adoc
  docs/images/Typee_highlevel_architecture_diagram.png
Labels: documentation

#62 Update UC05 and UC11
  docs/DeveloperGuide.adoc
Labels: documentation

#63 Updates to use case and glossary
  docs/DeveloperGuide.adoc
Labels: documentation

#75 Updates in setting controller issue & enables tab command with lower case
  src/main/java/com/typee/logic/parser/TabCommandParser.java
  src/main/java/com/typee/ui/AppointmentWindow.java
  src/main/java/com/typee/ui/CalendarWindow.java
  src/main/java/com/typee/ui/GameWindow.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/Tab.java
  src/main/java/com/typee/ui/report/ReportWindow.java
  src/main/resources/view/ReportWindow.fxml
  src/test/java/com/typee/logic/commands/TabCommandTest.java
Labels: Type.Enhancement, priority.High, severity.High

#73 Undo/Redo v1.2
  src/main/java/com/typee/logic/commands/AddCommand.java
  src/main/java/com/typee/logic/commands/ClearCommand.java
  src/main/java/com/typee/logic/commands/DeleteCommand.java
  src/main/java/com/typee/logic/commands/EditCommand.java
  src/main/java/com/typee/logic/commands/FindCommand.java
  src/main/java/com/typee/logic/commands/ListCommand.java
  src/main/java/com/typee/logic/commands/RedoCommand.java
  src/main/java/com/typee/logic/commands/UndoCommand.java
  src/main/java/com/typee/logic/commands/exceptions/NullRedoableActionException.java
  src/main/java/com/typee/logic/commands/exceptions/NullUndoableActionException.java
  src/main/java/com/typee/logic/parser/TypeeParser.java
  src/main/java/com/typee/model/HistoryManager.java
  src/main/java/com/typee/model/Model.java
  src/main/java/com/typee/model/ModelManager.java
  src/main/java/com/typee/storage/StorageManager.java
  src/test/java/com/typee/logic/LogicManagerTest.java
  src/test/java/com/typee/logic/commands/AddCommandTest.java
  src/test/java/com/typee/logic/commands/ClearCommandTest.java
  src/test/java/com/typee/logic/commands/CommandTestUtil.java
  src/test/java/com/typee/logic/commands/DeleteCommandTest.java
  src/test/java/com/typee/logic/commands/EditCommandTest.java
  src/test/java/com/typee/logic/commands/FindCommandTest.java
  src/test/java/com/typee/logic/commands/RedoCommandTest.java
  src/test/java/com/typee/logic/commands/UndoCommandTest.java
  src/test/java/com/typee/model/AddressBookTest.java
  src/test/java/com/typee/model/ModelManagerTest.java
  src/test/java/com/typee/storage/JsonAddressBookStorageTest.java
  src/test/java/com/typee/storage/StorageManagerTest.java
  src/test/java/com/typee/testutil/TypicalPersons.java
Labels: Type.Enhancement, priority.High, status.Ongoing

#69 Delete additional user story from DG
  docs/DeveloperGuide.adoc
Labels: documentation

#83 Engagement conflict detection
  src/main/java/com/typee/logic/commands/EditCommand.java
  src/main/java/com/typee/logic/parser/AddCommandParser.java
  src/main/java/com/typee/model/AddressBook.java
  src/main/java/com/typee/model/engagement/AttendeeList.java
  src/main/java/com/typee/model/engagement/Engagement.java
  src/main/java/com/typee/model/engagement/EngagementConflictChecker.java
  src/main/java/com/typee/model/engagement/UniqueEngagementList.java
  src/main/java/com/typee/model/engagement/exceptions/InvalidTimeException.java
  src/main/java/com/typee/model/util/SampleDataUtil.java
  src/main/java/com/typee/storage/JsonAdaptedPerson.java
Labels: Type.Enhancement, priority.High

#77 Implement typing game skeleton using JavaFX
  docs/DeveloperGuide.adoc
  src/main/java/com/typee/game/Player.java
  src/main/java/com/typee/game/Words.java
  src/main/java/com/typee/logic/parser/TabCommandParser.java
  src/main/java/com/typee/logic/parser/TypeeParser.java
  src/main/java/com/typee/ui/AppointmentWindow.java
  src/main/java/com/typee/ui/CalendarWindow.java
  src/main/java/com/typee/ui/EngagementCard.java
  src/main/java/com/typee/ui/EngagementListPanel.java
  src/main/java/com/typee/ui/GameWindow.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/ReportWindow.java
  src/main/java/com/typee/ui/game/GameBody.java
  src/main/java/com/typee/ui/game/GameWindow.java
  src/main/java/com/typee/ui/game/MovingWord.java
  src/main/java/com/typee/ui/game/PlayerInformation.java
  src/main/java/com/typee/ui/game/StartWindow.java
  src/main/java/com/typee/ui/game/TextHighlighter.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EngagementListPanel.fxml
  src/main/resources/view/GameBody.fxml
  src/main/resources/view/GameWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MovingWord.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PlayerInformation.fxml
  src/main/resources/view/StartWindow.fxml
  tabMenus.json
Labels: Type.Enhancement, priority.Low, status.Ongoing, type.Story

#74 Calendar Window UI
  docs/DeveloperGuide.adoc
  src/main/java/com/typee/ui/CalendarWindow.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/calendar/CalendarWindow.java
  src/main/java/com/typee/ui/calendar/IndividualDatePane.java
  src/main/resources/view/Calendar.css
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/IndividualDatePane.fxml
Labels: Type.Enhancement, priority.High, status.Ongoing

#87 Implement vanilla version of typing game
  docs/DeveloperGuide.adoc
  src/main/java/com/typee/logic/commands/EditCommand.java
  src/main/java/com/typee/logic/parser/AddCommandParser.java
  src/main/java/com/typee/model/AddressBook.java
  src/main/java/com/typee/model/engagement/AttendeeList.java
  src/main/java/com/typee/model/engagement/Engagement.java
  src/main/java/com/typee/model/engagement/EngagementConflictChecker.java
  src/main/java/com/typee/model/engagement/UniqueEngagementList.java
  src/main/java/com/typee/model/engagement/exceptions/InvalidTimeException.java
  src/main/java/com/typee/model/util/SampleDataUtil.java
  src/main/java/com/typee/storage/JsonAdaptedPerson.java
  src/main/java/com/typee/ui/CalendarWindow.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/calendar/CalendarWindow.java
  src/main/java/com/typee/ui/calendar/IndividualDatePane.java
  src/main/resources/view/Calendar.css
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/IndividualDatePane.fxml
Labels: Type.Enhancement, priority.Low, type.Story

#85 Game branch
  docs/DeveloperGuide.adoc
  src/main/java/com/typee/game/Player.java
  src/main/java/com/typee/game/Words.java
  src/main/java/com/typee/logic/parser/TabCommandParser.java
  src/main/java/com/typee/ui/GameWindow.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/game/GameBody.java
  src/main/java/com/typee/ui/game/GameWindow.java
  src/main/java/com/typee/ui/game/MovingWord.java
  src/main/java/com/typee/ui/game/PlayerInformation.java
  src/main/java/com/typee/ui/game/StartWindow.java
  src/main/java/com/typee/ui/game/TextHighlighter.java
  src/main/resources/view/GameBody.fxml
  src/main/resources/view/GameWindow.fxml
  src/main/resources/view/MovingWord.fxml
  src/main/resources/view/PlayerInformation.fxml
  src/main/resources/view/StartWindow.fxml
Labels: Type.Enhancement, priority.Low, type.Story

#98 Update UGDG game feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  docs/images/GameWindowClassDiagram.png
Labels: documentation

#95 Updates in Developer Guide
  .gitignore
  docs/DeveloperGuide.adoc
  docs/diagrams/GenerateDocumentSequenceDiagram.puml
  docs/diagrams/PdfCommandClassDiagram.puml
  docs/diagrams/PdfUtilClassDiagram.puml
  docs/diagrams/TabClassDiagram.puml
  docs/diagrams/TabCommandClassDiagram.puml
  docs/diagrams/fetchTabInformationActivityDiagram.puml
  docs/images/PdfCommandClassDiagram.png
  docs/images/PdfUtilClassDiagram.png
  docs/images/TabClassDiagram.png
  docs/images/TabCommandClassDiagram.png
  docs/images/fetchTabInformationActivityDiagram.png
  docs/images/interview_template.png
  docs/images/pdf-report/Report_ClassDiagram.png
Labels: documentation

#94 Implement sort command
  src/main/java/com/typee/commons/core/Messages.java
  src/main/java/com/typee/logic/Logic.java
  src/main/java/com/typee/logic/LogicManager.java
  src/main/java/com/typee/logic/commands/ClearCommand.java
  src/main/java/com/typee/logic/commands/DeleteCommand.java
  src/main/java/com/typee/logic/commands/EditCommand.java
  src/main/java/com/typee/logic/commands/ExitCommand.java
  src/main/java/com/typee/logic/commands/FindCommand.java
  src/main/java/com/typee/logic/commands/SortCommand.java
  src/main/java/com/typee/logic/parser/ParserUtil.java
  src/main/java/com/typee/logic/parser/SortCommandParser.java
  src/main/java/com/typee/logic/parser/TypeeParser.java
  src/main/java/com/typee/model/Model.java
  src/main/java/com/typee/model/ModelManager.java
  src/main/java/com/typee/model/person/Name.java
  src/main/java/com/typee/model/person/Person.java
  src/main/java/com/typee/model/util/EngagementComparator.java
  src/main/java/com/typee/storage/JsonAdaptedEngagement.java
  src/main/java/com/typee/storage/JsonSerializableEngagementList.java
  src/main/java/com/typee/ui/MainWindow.java
  src/test/java/com/typee/logic/LogicManagerTest.java
  src/test/java/com/typee/logic/commands/AddCommandTest.java
  src/test/java/com/typee/logic/commands/DeleteCommandTest.java
  src/test/java/com/typee/logic/commands/SortCommandTest.java
Labels: Type.Enhancement

#113 Implements pdf command with report window ui
  .gitignore
  .travis.yml
  build.gradle
  docs/images/appveyor/add-project-1.png
  docs/images/appveyor/add-project-2.png
  docs/images/appveyor/add-project-3.png
  docs/images/appveyor/login.png
  docs/images/appveyor/project-settings-1.png
  docs/images/appveyor/project-settings-2.png
  docs/images/appveyor/project-settings-3.png
  gradlew
  src/main/java/com/typee/commons/core/Config.java
  src/main/java/com/typee/commons/util/FileUtil.java
  src/main/java/com/typee/commons/util/JsonUtil.java
  src/main/java/com/typee/commons/util/PdfUtil.java
  src/main/java/com/typee/logic/commands/PdfCommand.java
  src/main/java/com/typee/logic/parser/CliSyntax.java
  src/main/java/com/typee/logic/parser/PdfCommandParser.java
  src/main/java/com/typee/logic/parser/TypeeParser.java
  src/main/java/com/typee/model/UserPrefs.java
  src/main/java/com/typee/model/engagement/AttendeeList.java
  src/main/java/com/typee/model/report/Report.java
  src/main/java/com/typee/storage/JsonTypeeStorage.java
  src/main/java/com/typee/ui/MainWindow.java
  src/main/java/com/typee/ui/ReportWindow.java
  src/main/java/com/typee/ui/report/ReportWindow.java
  src/main/resources/document_template.properties
  src/main/resources/images/btn_refresh.png
  src/main/resources/images/btn_remove.png
  src/main/resources/images/company_logo_sample.png
  src/main/resources/tabMenus.json
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ReportWindow.fxml
Labels: Type.Enhancement, priority.High

#119 Fix bug for tabMenus.json
  docs/images/Ui.png
  src/main/java/com/typee/MainApp.java
  src/main/java/com/typee/commons/core/Config.java
  src/main/java/com/typee/model/UserPrefs.java
  src/main/resources/images/btn_next_l.png
  src/main/resources/images/btn_next_r.png
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/DarkTheme.css
  tabMenus.json
Labels: Type.Bug, documentation

#122 Additional updates in pdf feature with seperate document format for appointment
  docs/DeveloperGuide.adoc
  src/main/java/com/typee/commons/util/PdfUtil.java
  src/main/resources/document_template.properties
Labels: Type.Enhancement

#121 Updates Developer Guide and User Guide for v1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/PdfCommandClassDiagram.puml
  docs/diagrams/TabCommandClassDiagram.puml
  docs/images/PdfCommandClassDiagram.png
  docs/images/TabCommandClassDiagram.png
  docs/images/Typee_highlevel_architecture_diagram.png
  docs/images/pdf_1.png
  docs/images/pdf_2.PNG
  docs/images/pdf_delete.PNG
  docs/images/pdf_delete_after.PNG
  docs/images/pdf_sample.PNG
  docs/images/tab_1_default.PNG
  docs/images/tab_2.PNG
  docs/images/tab_3.PNG
Labels: documentation

#124 Game branch
  src/main/java/com/typee/game/Player.java
  src/main/java/com/typee/game/Words.java
  src/main/java/com/typee/logic/parser/TabCommandParser.java
  src/main/java/com/typee/ui/game/GameBody.java
  src/main/java/com/typee/ui/game/GameWindow.java
  src/main/java/com/typee/ui/game/MovingWord.java
  src/main/java/com/typee/ui/game/TextHighlighter.java
  src/main/resources/tabMenus.json
  src/main/resources/view/GameBody.fxml
  src/main/resources/view/GameWindow.css
  src/main/resources/view/GameWindow.fxml
  src/main/resources/view/MovingWord.fxml
  src/main/resources/view/PlayerInformation.fxml
  tabMenus.json
Labels: Type.Enhancement

#130 Fix GameWindow bug #129
  src/main/java/com/typee/ui/game/GameWindow.java
  src/main/java/com/typee/ui/game/StartWindow.java
  tabMenus.json
Labels: Type.Enhancement

#125 Update documentation
  README.adoc
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/GameWindow.png
  docs/images/github-logo.png
  docs/images/java-logo.png
  docs/images/javafx-logo.png
  docs/images/json-logo.png
  docs/images/junit5-logo.png
  docs/images/travis-logo.png
  docs/team/jun-ha0.adoc
  src/main/java/com/typee/ui/MainWindow.java
Labels: documentation

#134 Updates User Guide
  .gitignore
  README.adoc
  docs/UserGuide.adoc
  docs/images/pdf_1.png
  docs/images/pdf_2.png
  docs/images/pdf_delete.png
  docs/images/pdf_delete_after.png
  docs/images/pdf_function_btns.png
  docs/images/pdf_sample.png
  docs/images/tab_1_default.png
  docs/images/tab_2.png
  docs/images/tab_3.png
Labels: documentation

#135 Updated Add Engagement Command in User Guide
  docs/UserGuide.adoc
  docs/images/add_1.png
  docs/images/add_2.png
Labels: documentation
